services:
  # NextJS v14 app running on development mode
  acaptutorials.github.io-latest:
    container_name: acaptutorials-docs-latest
    image: acaptutorials/acaptutorials.github.io:latest
    env_file:
      - ./docs/.env
    build:
      context: ./docs
      dockerfile: Dockerfile
      target: development
    networks:
      - acaptutorials.github.io-latest
    volumes:
      - ./docs:/opt/docs
      - /opt/docs/node_modules
      - /opt/docs/.next
    ports:
      - "3000:3000"

networks:
  acaptutorials.github.io-latest:
    name: acaptutorials.github.io-latest
    external: false
