# Deploy the development image to Docker Hub
name: Push to Docker Hub

on:
  release:
    types: [published]
  push:
    branches:
      - feat/acaptutorials-54

jobs:
  docker-build-push:
    name: Development Image to Dockerhub
    # if: github.event.release.target_commitish == 'master' && vars.DOCKERHUB_USERNAME != ''
    if: vars.DOCKERHUB_USERNAME != ''
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Create env variables
        run: cp docs/.env.example docs/.env

      - name: Build Image
        run: docker compose -f docker-compose.dev.yml build

      - name: Push Image to Docker Hub
        run: docker compose -f docker-compose.dev.yml push
